on:
  workflow_call:
    inputs:
      branch:
        description: The branch to check out
        required: true
        type: string
      caller_job_name:
        description: The name of the job that calls this one
        required: true
        type: string
      command:
        description: The command to run
        required: true
        type: string
      node_version:
        default: '22'
        description: The Node version to use
        required: false
        type: string
      notify_pr:
        default: false
        description: Whether to notify the PR about failures/success runs
        required: false
        type: string
      site_artifact_name:
        default: ''
        description: The name of the artifact to download
        required: false
        type: string
      site_artifact_path:
        default: ''
        description: The path to the artifact to download
        required: false
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: https://registry.npmjs.org

      - if: ${{ inputs.site_artifact_name && inputs.site_artifact_path }}
        name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.site_artifact_name }}
          path: ${{ inputs.site_artifact_path }}

      - name: Run Command
        run: |
          set +e
          ${{ inputs.command }}
          EXIT_CODE=$?
          set -e

          if ${{ inputs.notify_pr }}; then
            if [ $EXIT_CODE -eq 0 ]; then
              echo "status=success" >> $GITHUB_ENV
            else
              echo "status=fail" >> $GITHUB_ENV
            fi
          else
            exit $EXIT_CODE
          fi

      - id: job_log_url
        if: github.event_name == 'pull_request' && inputs.notify_pr == 'true'
        name: Get Job Log URL
        uses: Tiryoh/gha-jobid-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          job_name: ${{ inputs.caller_job_name }} / ${{ github.job }}

      - if: github.event_name == 'pull_request' && inputs.notify_pr == 'true' && env.status == 'fail'
        name: Pull Request Failure Comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: ${{ inputs.caller_job_name }}
          message: |
            :warning: Latest run of ${{ inputs.caller_job_name }} **failed**: ${{ steps.job_log_url.outputs.html_url }}

      - if: github.event_name == 'pull_request' && inputs.notify_pr == 'true' && env.status == 'success'
        name: Pull Request Success Comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: ${{ inputs.caller_job_name }}
          message: |
            :white_check_mark: Latest run of ${{ inputs.caller_job_name }} **succeeded**: ${{ steps.job_log_url.outputs.html_url }}
